### ISSUE TITLE
set up main menu. 200 pts

### ISSUE THREAD

**Issue by zhiqinlei1998** [ucsb-cs56-webapps/ucsb-cs56-gauchoalarm#6]
create Create Alarm and Join Alarm in the webapp menu. 
After creating an Alarm, users can type their Time and Purpose. If they want to join an Alarm, they just need to type their Key of Alarm.  - 200 points

**Comment by DennisZZH** [comment]
OK. + 200 pts

**Comment by DennisZZH** [comment]
Issue done. + 200 pts
