### ISSUE TITLE
generate a unique key. 100 pts

### ISSUE THREAD

**Issue by zhiqinlei1998** [ucsb-cs56-webapps/ucsb-cs56-gauchoalarm#7]
we need a function to create a random and unique key for users to join alarm. This key need to a 8 length and alpha or numbers.

**Comment by kheff16** [comment]
Solved using hash code from string generated description

**Comment by DennisZZH** [comment]
Ok. 100 pts.

**Comment by DennisZZH** [comment]
Issue done. + 100 pts.
