### ISSUE TITLE
take input from the "Create Alarm" tag into the database. 400 pts

### ISSUE THREAD

**Issue by zhiqinlei1998** [ucsb-cs56-webapps/ucsb-cs56-gauchoalarm#8]
Properly set up and connect the database. When users input their Time and Purpose under the "Create Alarm" tag and hit the "Submit" button, the input will be written to the database.

**Comment by DennisZZH** [comment]
OK. 200 pts.

**Comment by DennisZZH** [comment]
Issue done. + 400 pts
